-- ─── 0008: Per-partner Looker Studio impact views ───────────────────────────
--
-- Pattern B from CLAUDE.md §11: one PostgreSQL view per Corporate Partner so
-- Looker Studio dashboards bound to a partner physically cannot read another
-- partner's data — defense-in-depth on top of any Looker UI-level filters.
--
-- The view is generated by a PL/pgSQL function so onboarding a new partner is
-- one SQL call, not a hand-edited migration.
--
-- Note on the schema inconsistency this works around:
--   * project_locations.funder_id           → corporate_partners.id  (org row)
--   * corporate_unlock_milestones.corporate_partner_id → users.id    (user row)
-- The function takes the corporate_partners.id (org row) as input and joins
-- through users.partner_id to bridge.

CREATE OR REPLACE FUNCTION create_partner_impact_view(partner_org_id uuid)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    short_id   text := replace(partner_org_id::text, '-', '');
    view_name  text := 'v_partner_' || left(short_id, 8) || '_impact';
    sql_stmt   text;
BEGIN
    sql_stmt := format($f$
        CREATE OR REPLACE VIEW %I AS
        WITH partner_user_ids AS (
            SELECT id AS user_id
            FROM users
            WHERE partner_id = %L
        ),
        latest_audit AS (
            -- Per CLAUDE.md §2: count only the most recent audit per location.
            SELECT DISTINCT ON (project_location_id)
                project_location_id,
                survey_date,
                trees_planted,
                trees_alive,
                round(trees_alive::numeric / nullif(trees_planted, 0) * 100, 1) AS survival_rate
            FROM tree_survival_checks
            ORDER BY project_location_id, survey_date DESC
        )
        SELECT
            -- Milestone progress (from existing v_corporate_partner_scorecard shape)
            cum.milestone_type,
            cum.threshold_value,
            cum.current_value,
            cum.status                          AS milestone_status,
            cum.verified_at                     AS milestone_verified_at,
            -- Per-location survival snapshot
            pl.id                               AS project_location_id,
            pl.name                             AS project_location_name,
            la.survey_date                      AS latest_audit_date,
            la.trees_planted,
            la.trees_alive,
            la.survival_rate
        FROM corporate_unlock_milestones cum
        LEFT JOIN partner_user_ids pu ON pu.user_id = cum.corporate_partner_id
        LEFT JOIN project_locations pl ON pl.funder_id = %L
        LEFT JOIN latest_audit la ON la.project_location_id = pl.id
        WHERE pu.user_id IS NOT NULL
           OR pl.id IS NOT NULL;
    $f$, view_name, partner_org_id, partner_org_id);

    EXECUTE sql_stmt;

    -- Grant read to the Looker Studio role (see CLAUDE.md §11 setup).
    EXECUTE format('GRANT SELECT ON %I TO looker_reader', view_name);

    RETURN view_name;
END;
$$;

COMMENT ON FUNCTION create_partner_impact_view(uuid) IS
    'Generates v_partner_<short>_impact for a Corporate Partner. Idempotent. Returns the view name.';

-- ── Drop helper ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION drop_partner_impact_view(partner_org_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    short_id   text := replace(partner_org_id::text, '-', '');
    view_name  text := 'v_partner_' || left(short_id, 8) || '_impact';
BEGIN
    EXECUTE format('DROP VIEW IF EXISTS %I', view_name);
END;
$$;

-- ── Example invocation (commented — uncomment and substitute real UUID) ──────
-- SELECT create_partner_impact_view('00000000-0000-0000-0000-000000000000'::uuid);
--
-- After running the function, copy the connection details from CLAUDE.md §11
-- into Looker Studio and point a new data source at the returned view name.
